# Site settings
title: Tim Peterson
email: hi@timrpeterson.com
description: > # this means to ignore newlines until "baseurl:"
  Tim Peterson blog. Molecular biology and programming. Tiny things that rule the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.timrpeterson.com" # the base hostname & protocol for your site
twitter_username: timrpeterson
github_username:  tim-peterson
linkedin_username:  petersontimr

# Build settings
markdown: kramdown
